version: "3.9"

services:
  # (UserService)
  user-service:
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

  
  specialist-service:
    build:
      context: .
      dockerfile: SpecialistService.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

  # RabbitMQ (with Management UI)
 # RabbitMQ с Management UI
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"  # Порт RabbitMQ (AMQP)
      - "15672:15672"  # Порт для Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

