// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpecialistService.API.Repositories;

#nullable disable

namespace SpecialistService.API.Migrations
{
    [DbContext(typeof(SpecialistDbContext))]
    [Migration("20241119092856_Edit_options_spec")]
    partial class Edit_options_spec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpecialistService.API.Models.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialistsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistsId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SpecialistService.API.Models.Specialists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("SpecialistService.API.Models.Skills", b =>
                {
                    b.HasOne("SpecialistService.API.Models.Specialists", "Specialists")
                        .WithMany("Skills")
                        .HasForeignKey("SpecialistsId");

                    b.Navigation("Specialists");
                });

            modelBuilder.Entity("SpecialistService.API.Models.Specialists", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
